name: AssetVault CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 1. Test & Build Frontend
  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      - name: Build
        working-directory: ./frontend
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: https://assetvault-0fu0.onrender.com

  # 2. Test Backend
  backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'
      - name: Install dependencies
        working-directory: ./backend
        run: npm install

  # 3. Test Smart Contracts
  contracts:
    name: Build & Test Soroban Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.77.2
          targets: wasm32-unknown-unknown
      - name: Build Contracts
        working-directory: ./contracts
        run: |
          rm -f Cargo.lock
          cargo build --target wasm32-unknown-unknown --release
      - name: Run Tests
        working-directory: ./contracts
        run: cargo test
